### ISSUE TITLE
Can we use VSCode for the assignments?

### ISSUE THREAD

**Issue by andyw1589** [karansher/computer-graphics-raster-images#1]
I'm on Windows and the footnote says I need the Visual Studio 2015+ compiler, but I really don't want to download Visual Studio because it's so bulky.....is it possible to finish the assignments in VSCode instead?

**Comment by philip-huang** [comment]
VSCode is a code editor, not a _compiler_. You may use any code editor but you will need a compiler on Windows to compile the C++ code

**Comment by abhimadan** [comment]
We highly recommend using Visual Studio for your assignments since it becomes much easier to work with OpenGL in later assignments. Alternatives like cygwin and WSL work for earlier assignments but students have run into GPU driver issues later on, so it's a good investment to get Visual Studio working now to avoid headaches with later, more challenging, assignments.

**Comment by andyw1589** [comment]
pain
