### ISSUE TITLE
cmake: The term 'cmake' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by ttyhhu** [karansher/computer-graphics-raster-images#10]
![cmake](https://user-images.githubusercontent.com/60581861/190034810-30f266f9-21cb-448d-91e8-6d5571c262f0.jpg)
cmake in terminal wouldn't work but I can build with the build button below.

**Comment by abhimadan** [comment]
This is probably because cmake isn't installed on your machine. To run it via powershell/command line you need to download it from their website: https://cmake.org/

You can build cmake projects directly in Visual Studio, which is probably what you did here, but I don't have much experience with that feature. I think there are some differences between running cmake on the command line but if it works then you should be fine.

**Comment by ttyhhu** [comment]
I see. Thank you! :)
