### ISSUE TITLE
What's supposed to happen when you run the compiled program for the first time?

### ISSUE THREAD

**Issue by andyw1589** [karansher/computer-graphics-raster-images#4]
When you first download the assignment, compile it, then run it, is anything supposed to happen? I just wanna make sure I didn't break anything.....

**Comment by abhimadan** [comment]
If it compiles successfully then you're good to go. Without implementing anything in the assignment, running the program will do nothing.

**Comment by yixinlok** [comment]
<img width="567" alt="Screenshot 2022-09-13 at 6 59 11 PM" src="https://user-images.githubusercontent.com/81039266/190023861-c564091a-9763-4dbb-a7b7-2a1efb7d3757.png">
is this normal? I didn't implement anything either and ran it but there seems to be an error in main

**Comment by abhimadan** [comment]
Please take a look at the note for Windows users at the bottom of the readme. This is expected because the executable can only be run from the `build` folder.

**Comment by yixinlok** [comment]
I did run it from the build folder though

**Comment by abhimadan** [comment]
No, based on the output it looks like you're running it from your home directory, since your terminal shows the`~` symbol for your current directory (either that or you clicked the directory from the folder in Finder). To run it from the build folder, open a terminal, change your directory to your build folder, and then call `./raster`.
