### ISSUE TITLE
Demosaic edges problem(last row and last column)

### ISSUE THREAD

**Issue by cccccz** [karansher/computer-graphics-raster-images#81]
![image](https://user-images.githubusercontent.com/60713799/191433840-f6e1b6eb-fd11-4d24-9724-0431e2e747c7.png)
1. should the output look like this?
![image](https://user-images.githubusercontent.com/60713799/191433931-95632dbb-18a6-40f0-9caa-e4ee80a4f533.png)
2. I tried really hard to fix the last row and the last column but I really don't know how to fix it. I tried for 3 hours but I get vector subscript out of range every time. I feel so sad right now.....

**Comment by abhimadan** [comment]
I don't entirely understand what issue you're running into based on the two images you posted. Are your edge pixels completely black, or are you getting a mosaic pattern on some of the outer edges? Either way, it suggests a bug, since you should get a somewhat reasonable value if you follow the same principles as demosaicing the interior pixels. However, don't worry too much if you feel that you've wasted a lot of time on it, since you will still get most of the marks for that part of the assignment if the interior of the image looks good.

**Comment by cccccz** [comment]
I think the problem is: when I try to access the bottom line and the last column, i went out of boundary somewhere

**Comment by cccccz** [comment]
> I don't entirely understand what issue you're running into based on the two images you posted. Are your edge pixels completely black, or are you getting a mosaic pattern on some of the outer edges? Either way, it suggests a bug, since you should get a somewhat reasonable value if you follow the same principles as demosaicing the interior pixels. However, don't worry too much if you feel that you've wasted a lot of time on it, since you will still get most of the marks for that part of the assignment if the interior of the image looks good.

ty!
